package main

func getCountry(id int) string {
	switch id {
	case 1:
		return "Алания"
	case 2:
		return "Алатрис"
	case 3:
		return "Алезия"
	case 4:
		return "Ализия"
	case 5:
		return "Алляндия"
	case 6:
		return "Алмаль"
	case 7:
		return "Алция"
	case 8:
		return "Герания"
	case 9:
		return "Гератрис"
	case 10:
		return "Герезия"
	case 11:
		return "Геризия"
	case 12:
		return "Герляндия"
	case 13:
		return "Гермаль"
	case 14:
		return "Герция"
	case 15:
		return "Голания"
	case 16:
		return "Голатрис"
	case 17:
		return "Голезия"
	case 18:
		return "Голизия"
	case 19:
		return "Голляндия"
	case 20:
		return "Голмаль"
	case 21:
		return "Голция"
	case 22:
		return "Индания"
	case 23:
		return "Индатрис"
	case 24:
		return "Индезия"
	case 25:
		return "Индизия"
	case 26:
		return "Индляндия"
	case 27:
		return "Индмаль"
	case 28:
		return "Индция"
	case 29:
		return "Испания"
	case 30:
		return "Испатрис"
	case 31:
		return "Испезия"
	case 32:
		return "Испизия"
	case 33:
		return "Испляндия"
	case 34:
		return "Испмаль"
	case 35:
		return "Испция"
	case 36:
		return "Малания"
	case 37:
		return "Малатрис"
	case 38:
		return "Малезия"
	case 39:
		return "Мализия"
	case 40:
		return "Малляндия"
	case 41:
		return "Малмаль"
	case 42:
		return "Малция"
	case 43:
		return "Росания"
	case 44:
		return "Росатрис"
	case 45:
		return "Росезия"
	case 46:
		return "Росизия"
	case 47:
		return "Росляндия"
	case 48:
		return "Росмаль"
	case 49:
		return "Росция"
	case 50:
		return "Румания"
	case 51:
		return "Руматрис"
	case 52:
		return "Румезия"
	case 53:
		return "Румизия"
	case 54:
		return "Румляндия"
	case 55:
		return "Руммаль"
	case 56:
		return "Румция"
	case 57:
		return "Турания"
	case 58:
		return "Туратрис"
	case 59:
		return "Турезия"
	case 60:
		return "Туризия"
	case 61:
		return "Турляндия"
	case 62:
		return "Турмаль"
	case 63:
		return "Турция"
	case 64:
		return "Финания"
	case 65:
		return "Финатрис"
	case 66:
		return "Финезия"
	case 67:
		return "Финизия"
	case 68:
		return "Финляндия"
	case 69:
		return "Финмаль"
	case 70:
		return "Финция"
	}
	return ""
}

func generateCountry() {
	for i := 1; i <= 70; i++ {
	}
}
