package main

func getCountryName(id int) string {
	switch id {
	case 1:
		return "Алания"
	case 2:
		return "Алатрис"
	case 3:
		return "Алезия"
	case 4:
		return "Ализия"
	case 5:
		return "Алляндия"
	case 6:
		return "Алмаль"
	case 7:
		return "Алция"
	case 8:
		return "Герания"
	case 9:
		return "Гератрис"
	case 10:
		return "Герезия"
	case 11:
		return "Геризия"
	case 12:
		return "Герляндия"
	case 13:
		return "Гермаль"
	case 14:
		return "Герция"
	case 15:
		return "Голания"
	case 16:
		return "Голатрис"
	case 17:
		return "Голезия"
	case 18:
		return "Голизия"
	case 19:
		return "Голляндия"
	case 20:
		return "Голмаль"
	case 21:
		return "Голция"
	case 22:
		return "Индания"
	case 23:
		return "Индатрис"
	case 24:
		return "Индезия"
	case 25:
		return "Индизия"
	case 26:
		return "Индляндия"
	case 27:
		return "Индмаль"
	case 28:
		return "Индция"
	case 29:
		return "Испания"
	case 30:
		return "Испатрис"
	case 31:
		return "Испезия"
	case 32:
		return "Испизия"
	case 33:
		return "Испляндия"
	case 34:
		return "Испмаль"
	case 35:
		return "Испция"
	case 36:
		return "Малания"
	case 37:
		return "Малатрис"
	case 38:
		return "Малезия"
	case 39:
		return "Мализия"
	case 40:
		return "Малляндия"
	case 41:
		return "Малмаль"
	case 42:
		return "Малция"
	case 43:
		return "Росания"
	case 44:
		return "Росатрис"
	case 45:
		return "Росезия"
	case 46:
		return "Росизия"
	case 47:
		return "Росляндия"
	case 48:
		return "Росмаль"
	case 49:
		return "Росция"
	case 50:
		return "Румания"
	case 51:
		return "Руматрис"
	case 52:
		return "Румезия"
	case 53:
		return "Румизия"
	case 54:
		return "Румляндия"
	case 55:
		return "Руммаль"
	case 56:
		return "Румция"
	case 57:
		return "Турания"
	case 58:
		return "Туратрис"
	case 59:
		return "Турезия"
	case 60:
		return "Туризия"
	case 61:
		return "Турляндия"
	case 62:
		return "Турмаль"
	case 63:
		return "Турция"
	case 64:
		return "Финания"
	case 65:
		return "Финатрис"
	case 66:
		return "Финезия"
	case 67:
		return "Финизия"
	case 68:
		return "Финляндия"
	case 69:
		return "Финмаль"
	case 70:
		return "Финция"
	}
	return ""
}

func getCountryId(name string) int {
	switch name {
	case "Алания":
		return 1
	case "Алатрис":
		return 2
	case "Алезия":
		return 3
	case "Ализия":
		return 4
	case "Алляндия":
		return 5
	case "Алмаль":
		return 6
	case "Алция":
		return 7
	case "Герания":
		return 8
	case "Гератрис":
		return 9
	case "Герезия":
		return 10
	case "Геризия":
		return 11
	case "Герляндия":
		return 12
	case "Гермаль":
		return 13
	case "Герция":
		return 14
	case "Голания":
		return 15
	case "Голатрис":
		return 16
	case "Голезия":
		return 17
	case "Голизия":
		return 18
	case "Голляндия":
		return 19
	case "Голмаль":
		return 20
	case "Голция":
		return 21
	case "Индания":
		return 22
	case "Индатрис":
		return 23
	case "Индезия":
		return 24
	case "Индизия":
		return 25
	case "Индляндия":
		return 26
	case "Индмаль":
		return 27
	case "Индция":
		return 28
	case "Испания":
		return 29
	case "Испатрис":
		return 30
	case "Испезия":
		return 31
	case "Испизия":
		return 32
	case "Испляндия":
		return 33
	case "Испмаль":
		return 34
	case "Испция":
		return 35
	case "Малания":
		return 36
	case "Малатрис":
		return 37
	case "Малезия":
		return 38
	case "Мализия":
		return 39
	case "Малляндия":
		return 40
	case "Малмаль":
		return 41
	case "Малция":
		return 42
	case "Росания":
		return 43
	case "Росатрис":
		return 44
	case "Росезия":
		return 45
	case "Росизия":
		return 46
	case "Росляндия":
		return 47
	case "Росмаль":
		return 48
	case "Росция":
		return 49
	case "Румания":
		return 50
	case "Руматрис":
		return 51
	case "Румезия":
		return 52
	case "Румизия":
		return 53
	case "Румляндия":
		return 54
	case "Руммаль":
		return 55
	case "Румция":
		return 56
	case "Турания":
		return 57
	case "Туратрис":
		return 58
	case "Турезия":
		return 59
	case "Туризия":
		return 60
	case "Турляндия":
		return 61
	case "Турмаль":
		return 62
	case "Турция":
		return 63
	case "Финания":
		return 64
	case "Финатрис":
		return 65
	case "Финезия":
		return 66
	case "Финизия":
		return 67
	case "Финляндия":
		return 68
	case "Финмаль":
		return 69
	case "Финция":
		return 70
	}
	return 0
}
